# -*- coding: utf-8 -*-
"""MLM_v11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCIjVRdHc0wbpjnt97kB8--sBOKrPpGI
"""

!pip install xgboost shap --quiet

# MOmics-ML v11- z-score + log1p + importance pruning + class balance

import json, joblib, warnings
from pathlib import Path
import numpy as np
import pandas as pd

# robust pd.read_csv
_original_read_csv = pd.read_csv
def _safe_read_csv(*args, **kwargs):
    if "encoding" in kwargs:
        return _original_read_csv(*args, **kwargs)
    attempts = [
        dict(encoding="utf-8"),
        dict(encoding="latin-1"),
        dict(encoding="utf-8",  on_bad_lines="skip"),
        dict(encoding="latin-1", on_bad_lines="skip"),
        dict(encoding="latin-1", on_bad_lines="skip", engine="python"),
    ]
    last_err = None
    for extra in attempts:
        try:
            kw = {**extra, **kwargs}  # kwargs override
            return _original_read_csv(*args, **kw)
        except (UnicodeDecodeError, UnicodeError, pd.errors.ParserError) as e:
            last_err = e
            continue
    raise last_err
pd.read_csv = _safe_read_csv

import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, average_precision_score, roc_curve
from xgboost import XGBClassifier

warnings.filterwarnings("ignore")
np.random.seed(42)

# CONFIG: project-relative paths
PROJECT_ROOT = Path(__file__).resolve().parent
DISCOVERY_DIR = PROJECT_ROOT / "data" / "discovery"
REFERENCE_DIR = PROJECT_ROOT / "data" / "reference"
EXTERNAL_DIR = PROJECT_ROOT / "data" / "external_validation"
OUT_DIR = PROJECT_ROOT / "results" / "v11_run"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# toggles
BALANCE_METHOD = "synthetic"          # "scale_pos_weight" | "synthetic" | "none"
SYNTH_TARGET = 100                     # samples per class when synthetic
SYNTH_NOISE_SD = 0.15                  # gaussian noise on z-scored data

N_RNA, N_PROT, N_MET = 12, 8, 5
KEEP_FRAC = 0.5                       # drop bottom 75% by gain importance
KEEP_MIN = 2                           # but keep at least this many per layer

N_SEEDS, N_FOLDS = 5, 5
SEED_BASE = 42

META_COLS = {"gene", "gene_id", "gene_name", "gene_type", "gene_status",
             "havana_gene", "full_length", "exon_length", "refseq_id",
             "Metabolite", "idx", "Unnamed: 0", "Gene", "Protein.Group", "Genes",
             "_mean", "_ensg", "_sym", "_g"}


def make_sub_params(spw=1.0):
    return dict(n_estimators=80, max_depth=3, learning_rate=0.05,
                reg_alpha=0.5, reg_lambda=2.0, min_child_weight=2,
                subsample=0.8, colsample_bytree=0.8,
                scale_pos_weight=spw,
                objective="binary:logistic", eval_metric="auc",
                use_label_encoder=False, verbosity=0)

FUSION_PARAMS = dict(n_estimators=30, max_depth=2, learning_rate=0.1, reg_lambda=5,
                     objective="binary:logistic", eval_metric="auc",
                     use_label_encoder=False, verbosity=0)


# DIABLO + mapping

def load_diablo_panel():
    df = pd.read_csv(REFERENCE_DIR / "diablo_multiomics_ranked_features_FDR_CLEAN.csv")
    df = df.sort_values("combined_weight", ascending=False)
    is_rna  = df["contributing_blocks"].isin(["transcriptomics", "proteomics;transcriptomics"])
    is_prot = df["contributing_blocks"].isin(["proteomics", "proteomics;transcriptomics"])
    is_met  = df["contributing_blocks"] == "metabolomics"
    return {"rna":  df.loc[is_rna,  "gene_symbol"].drop_duplicates().head(N_RNA).tolist(),
            "prot": df.loc[is_prot, "gene_symbol"].drop_duplicates().head(N_PROT).tolist(),
            "met":  df.loc[is_met,  "gene_symbol"].drop_duplicates().head(N_MET).tolist()}


def build_symbol_to_ensg():
    df = pd.read_csv(DISCOVERY_DIR / "rnaseq_washu_readcount.v4.0.tsv", sep="\t", low_memory=False)
    sample_cols = [c for c in df.columns if c.startswith("C3L") or c.startswith("C3N")]
    df["_mean"] = df[sample_cols].mean(axis=1)
    df["_ensg"] = df["gene_id"].astype(str).str.split(".").str[0]
    df = df.sort_values("_mean", ascending=False).drop_duplicates("gene_name")
    return dict(zip(df["gene_name"], df["_ensg"]))


def detect_samples(df, exclude=None):
    exclude = (exclude or set()) | META_COLS
    return [c for c in df.columns if c not in exclude]


def _filter_to_features(df, feat_col, target, sample_cols):
    sub = df[df[feat_col].isin(target)].copy()
    if sub.empty:
        return pd.DataFrame(index=target, columns=sample_cols, dtype=float)
    sub["_mean"] = sub[sample_cols].astype(float).mean(axis=1, skipna=True)
    sub = sub.sort_values("_mean", ascending=False).drop_duplicates(feat_col)
    matrix = pd.DataFrame(index=target, columns=sample_cols, dtype=float)
    for f in target:
        hit = sub[sub[feat_col] == f]
        if not hit.empty:
            matrix.loc[f] = hit.iloc[0][sample_cols].astype(float).values
    return matrix


# discovery loaders

def load_discovery_rna(features, manifest):
    df = pd.read_csv(DISCOVERY_DIR / "rnaseq_washu_readcount.v4.0.tsv", sep="\t", low_memory=False)
    sample_cols = [c for c in df.columns if c in manifest]
    matrix = _filter_to_features(df, "gene_name", features, sample_cols)
    n = matrix.notna().any(axis=1).sum()
    print(f"  RNA   discovery: {n}/{len(features)} features, {len(sample_cols)} samples (raw → log1p)")
    return np.log1p(matrix)


def load_discovery_prot(features, manifest):
    df = pd.read_csv(DISCOVERY_DIR / "proteome_mssm_per_gene_imputed.v4.0.tsv", sep="\t", low_memory=False)
    sample_cols = [c for c in df.columns if c in manifest]
    matrix = _filter_to_features(df, "gene", features, sample_cols)
    n = matrix.notna().any(axis=1).sum()
    print(f"  Prot  discovery: {n}/{len(features)} features, {len(sample_cols)} samples (already log2)")
    return matrix


def load_discovery_met(features, manifest):
    df = pd.read_csv(DISCOVERY_DIR / "metabolome_pnnl.v4.0.tsv", sep="\t", low_memory=False)
    sample_cols = [c for c in df.columns if c in manifest]
    matrix = _filter_to_features(df, "Metabolite", features, sample_cols)
    n = matrix.notna().any(axis=1).sum()
    print(f"  Met   discovery: {n}/{len(features)} features, {len(sample_cols)} samples (already log)")
    return matrix

# z-score

def fit_zscore(matrix):
    """matrix: (features × samples). Returns (mean Series, std Series) per feature."""
    means = matrix.mean(axis=1, skipna=True)
    stds  = matrix.std(axis=1, skipna=True).replace(0, 1.0)
    return means, stds


def apply_zscore(matrix, means, stds):
    """Z-score per feature, preserving NaN. Aligns to means.index."""
    out = matrix.copy()
    for f in out.index:
        if f in means.index and not pd.isna(means.loc[f]):
            out.loc[f] = (out.loc[f] - means.loc[f]) / stds.loc[f]
        else:
            out.loc[f] = np.nan
    return out


# external loaders

def _load_by_ensg(file_path, target_symbols, sym2ensg):
    if not file_path.exists(): return None
    df = pd.read_csv(file_path, sep="\t", low_memory=False)
    feat_col = df.columns[0]
    sample_cols = detect_samples(df, exclude={feat_col})
    df["_ensg"] = df[feat_col].astype(str).str.split(".").str[0]
    target_ensgs = {sym2ensg[s]: s for s in target_symbols if s in sym2ensg}
    sub = df[df["_ensg"].isin(target_ensgs.keys())].copy()
    if sub.empty:
        return pd.DataFrame(index=target_symbols, columns=sample_cols, dtype=float)
    sub["_sym"] = sub["_ensg"].map(target_ensgs)
    sub["_mean"] = sub[sample_cols].astype(float).mean(axis=1, skipna=True)
    sub = sub.sort_values("_mean", ascending=False).drop_duplicates("_sym")
    matrix = pd.DataFrame(index=target_symbols, columns=sample_cols, dtype=float)
    for _, r in sub.iterrows():
        matrix.loc[r["_sym"]] = r[sample_cols].astype(float).values
    return matrix


def _load_by_symbol(file_path, target_symbols, feat_col, sep="\t"):
    if not file_path.exists(): return None
    df = pd.read_csv(file_path, sep=sep, low_memory=False)
    sample_cols = detect_samples(df, exclude={feat_col})
    return _filter_to_features(df, feat_col, target_symbols, sample_cols)


def _load_cgga_prot(target_symbols):
    fp = EXTERNAL_DIR / "CGGA" / "CGGA_IDH_A_Proteomics_MS_Abundance_20250915.txt"
    df = pd.read_csv(fp, sep="\t", low_memory=False)
    sample_cols = detect_samples(df, exclude={"Protein.Group", "Genes"})
    df["Genes"] = df["Genes"].astype(str)
    df_exp = df.assign(_g=df["Genes"].str.split(";")).explode("_g")
    df_exp["_g"] = df_exp["_g"].str.strip()
    sub = df_exp[df_exp["_g"].isin(target_symbols)].copy()
    if sub.empty:
        return pd.DataFrame(index=target_symbols, columns=sample_cols, dtype=float)
    sub["_mean"] = sub[sample_cols].astype(float).mean(axis=1, skipna=True)
    sub = sub.sort_values("_mean", ascending=False).drop_duplicates("_g")
    matrix = pd.DataFrame(index=target_symbols, columns=sample_cols, dtype=float)
    for f in target_symbols:
        hit = sub[sub["_g"] == f]
        if not hit.empty:
            matrix.loc[f] = hit.iloc[0][sample_cols].astype(float).values
    return matrix


def maybe_log1p(matrix):
    """Auto-detect raw counts (max > 50) and apply log1p; else leave alone."""
    vals = matrix.values
    finite = vals[np.isfinite(vals)]
    if len(finite) > 0 and float(np.nanmax(finite)) > 50.0:
        return np.log1p(matrix), True
    return matrix, False


# class balance

def synthetic_balance(X, y, target_per_class=SYNTH_TARGET, noise_sd=SYNTH_NOISE_SD, rng=None):
    """Pad both classes to target_per_class by sampling existing samples + Gaussian noise.
    Operates on z-scored data, so noise_sd is on z-score units."""
    rng = rng or np.random.default_rng(SEED_BASE)
    X_arr = X.values
    y_arr = np.asarray(y)
    pieces_X, pieces_y = [X_arr], [y_arr]
    for cls in (0, 1):
        cls_mask = y_arr == cls
        n_cls = int(cls_mask.sum())
        if n_cls == 0:
            continue
        n_need = target_per_class - n_cls
        if n_need <= 0:
            continue
        cls_data = X_arr[cls_mask]
        idx = rng.integers(0, n_cls, size=n_need)
        synth = cls_data[idx] + rng.normal(0, noise_sd, size=(n_need, cls_data.shape[1]))
        pieces_X.append(synth)
        pieces_y.append(np.full(n_need, cls, dtype=int))
    X_out = pd.DataFrame(np.vstack(pieces_X), columns=X.columns)
    y_out = np.concatenate(pieces_y)
    return X_out, y_out


# CV

def cv_layer(X, y, name, balance=BALANCE_METHOD):
    if len(np.unique(y)) < 2:
        print(f"  {name}: single class"); return np.zeros(len(y)), float("nan")
    n_minor = min((y == 0).sum(), (y == 1).sum())
    n_folds = min(N_FOLDS, n_minor)
    if n_folds < 2:
        print(f"  {name}: only {n_minor} in minor class"); return np.zeros(len(y)), float("nan")

    spw = (y == 0).sum() / max((y == 1).sum(), 1) if balance == "scale_pos_weight" else 1.0

    oof = np.zeros((N_SEEDS, len(y)))
    fold_aucs, train_aucs = [], []
    for s_idx in range(N_SEEDS):
        seed = SEED_BASE + s_idx
        skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=seed)
        for tr, te in skf.split(X, y):
            X_tr, y_tr = X.iloc[tr], y[tr]
            if balance == "synthetic":
                X_tr, y_tr = synthetic_balance(X_tr, y_tr,
                                               rng=np.random.default_rng(seed * 1000 + s_idx))
            m = XGBClassifier(**make_sub_params(spw), random_state=seed)
            m.fit(X_tr, y_tr)
            oof[s_idx, te] = m.predict_proba(X.iloc[te])[:, 1]
            if len(np.unique(y[te])) > 1:
                fold_aucs.append(roc_auc_score(y[te], oof[s_idx, te]))
            train_aucs.append(roc_auc_score(y_tr, m.predict_proba(X_tr)[:, 1]))

    oof_mean = oof.mean(axis=0)
    auc = roc_auc_score(y, oof_mean)
    fa, ta = np.array(fold_aucs), np.array(train_aucs)
    print(f"  {name:5s}  OOF AUC={auc:.3f}  per-fold={fa.mean():.3f}±{fa.std():.3f}  "
          f"train={ta.mean():.3f}  gap={ta.mean()-fa.mean():+.3f}  "
          f"[n={len(y)}, {(y==1).sum()}+/{(y==0).sum()}-, balance={balance}]")
    return oof_mean, auc


def fuse(oof_dict, ids_dict, y_dict):
    all_ids = sorted(set().union(*(set(v) for v in ids_dict.values())))
    F = pd.DataFrame(index=all_ids, columns=["P_rna", "P_prot", "P_met"], dtype=float)
    Y = pd.Series(index=all_ids, dtype=float)
    for layer in ["rna", "prot", "met"]:
        for sid, p, lab in zip(ids_dict[layer], oof_dict[layer], y_dict[layer]):
            F.loc[sid, f"P_{layer}"] = p
            Y.loc[sid] = lab
    Y = Y.dropna().astype(int)
    F = F.loc[Y.index]

    skf = StratifiedKFold(N_FOLDS, shuffle=True, random_state=SEED_BASE)
    foof = np.zeros(len(Y))
    for tr, te in skf.split(F, Y):
        m = XGBClassifier(**FUSION_PARAMS, random_state=SEED_BASE)
        m.fit(F.iloc[tr], Y.iloc[tr])
        foof[te] = m.predict_proba(F.iloc[te])[:, 1]
    auc = roc_auc_score(Y, foof)
    pr  = average_precision_score(Y, foof)
    fpr, tpr, thr = roc_curve(Y, foof)
    youden = float(thr[np.argmax(tpr - fpr)])
    sens = float(((foof >= youden) & (Y == 1)).sum() / max((Y == 1).sum(), 1))
    spec = float(((foof <  youden) & (Y == 0)).sum() / max((Y == 0).sum(), 1))

    full = XGBClassifier(**FUSION_PARAMS, random_state=SEED_BASE)
    full.fit(F, Y)
    print(f"\n=== Fusion ===  AUROC={auc:.3f}  PR={pr:.3f}  Youden={youden:.3f}  Sens={sens*100:.1f}%  Spec={spec*100:.1f}%")
    return {"F": F, "Y": Y, "oof": foof, "auc": auc, "pr": pr,
            "youden": youden, "sens": sens, "spec": spec, "model": full}


# feature pruning

def prune_features(X, y, layer_name, balance=BALANCE_METHOD, keep_frac=KEEP_FRAC, min_keep=KEEP_MIN):
    spw = (y == 0).sum() / max((y == 1).sum(), 1) if balance == "scale_pos_weight" else 1.0
    X_tr, y_tr = X, y
    if balance == "synthetic":
        X_tr, y_tr = synthetic_balance(X, y)
    m = XGBClassifier(**make_sub_params(spw), random_state=SEED_BASE)
    m.fit(X_tr, y_tr)
    imp = pd.Series(m.feature_importances_, index=X.columns).sort_values(ascending=False)
    n_keep = max(min_keep, int(np.ceil(len(imp) * keep_frac)))
    surviving = imp.head(n_keep).index.tolist()
    print(f"  {layer_name:5s}  importances: {imp.round(3).to_dict()}")
    print(f"         keep {n_keep}/{len(imp)}: {surviving}")
    print(f"         drop: {imp.tail(len(imp) - n_keep).index.tolist()}")
    return surviving


# external scoring

def score_external(layer_matrices_zscored, sub_models, fusion_model, threshold):
    layer_probs = {}
    sample_set = None
    for layer, df in layer_matrices_zscored.items():
        if df is None or df.empty:
            continue
        X = df.T  # samples × features
        X = X.dropna(how="all")
        if X.empty:
            continue
        # XGBoost will handle remaining NaNs internally
        probs = sub_models[layer].predict_proba(X.values)[:, 1]
        layer_probs[layer] = pd.Series(probs, index=X.index)
        sample_set = set(X.index) if sample_set is None else sample_set | set(X.index)

    if sample_set is None: return None
    sids = sorted(sample_set)
    F = pd.DataFrame(index=sids, columns=["P_rna", "P_prot", "P_met"], dtype=float)
    for layer, ps in layer_probs.items():
        F.loc[ps.index, f"P_{layer}"] = ps.values
    fused = fusion_model.predict_proba(F.values)[:, 1]
    return pd.DataFrame({"sample": sids,
                         "P_rna": F["P_rna"].values, "P_prot": F["P_prot"].values, "P_met": F["P_met"].values,
                         "P_fused": fused, "call_GBM": (fused >= threshold).astype(int)})


# main
def main():
    print("=" * 72)
    print(f"MOmics-ML v11   balance={BALANCE_METHOD}   keep_frac={KEEP_FRAC}")
    print("=" * 72)

    panel = load_diablo_panel()
    print(f"\n=== DIABLO panel ===")
    print(f"  RNA  ({len(panel['rna']):2d}): {panel['rna']}")
    print(f"  Prot ({len(panel['prot']):2d}): {panel['prot']}")
    print(f"  Met  ({len(panel['met']):2d}): {panel['met']}")

    manifest_df = pd.read_csv(DISCOVERY_DIR / "all_subtypes.v5.1.tsv", sep="\t")
    manifest = {}
    for _, r in manifest_df.iterrows():
        if r["sample_type"] == "tumor":         manifest[r["case"]] = 1
        elif r["sample_type"] == "GTEx normal": manifest[r["case"]] = 0
    print(f"\n=== Manifest === {len(manifest)} cases  ({sum(manifest.values())} tumor, {len(manifest) - sum(manifest.values())} GTEx normal)")

    sym2ensg = build_symbol_to_ensg()

    #  load + log + z-score discovery
    print(f"\n=== Discovery loading ===")
    rna_raw  = load_discovery_rna(panel["rna"],   manifest)   # already log1p'd inside loader
    prot_raw = load_discovery_prot(panel["prot"], manifest)
    met_raw  = load_discovery_met(panel["met"],   manifest)

    # Z-score parameters per layer
    rna_mu, rna_sd   = fit_zscore(rna_raw)
    prot_mu, prot_sd = fit_zscore(prot_raw)
    met_mu, met_sd   = fit_zscore(met_raw)

    rna_z  = apply_zscore(rna_raw,  rna_mu,  rna_sd)
    prot_z = apply_zscore(prot_raw, prot_mu, prot_sd)
    met_z  = apply_zscore(met_raw,  met_mu,  met_sd)

    # Drop features that are entirely NaN (e.g., PRKN missing)
    def trim(matrix):
        keep = matrix.notna().any(axis=1)
        return matrix.loc[keep]
    rna_z, prot_z, met_z = trim(rna_z), trim(prot_z), trim(met_z)

    blocks = {}
    for layer, ranked in [("rna", rna_z), ("prot", prot_z), ("met", met_z)]:
        X = ranked.T
        keep = X.notna().any(axis=1)
        X = X.loc[keep]
        y = np.array([manifest[s] for s in X.index], dtype=int)
        blocks[layer] = {"X": X, "y": y, "ids": list(X.index)}
        print(f"  {layer}: X shape = {X.shape}, y = {(y==1).sum()}+/{(y==0).sum()}-")

    # Phase 1: CV on full panel to see baseline
    print(f"\n=== Phase 1: CV on full DIABLO panel (z-scored) ===")
    for layer in ["rna", "prot", "met"]:
        cv_layer(blocks[layer]["X"], blocks[layer]["y"], layer)

    # Phase 2: prune to top KEEP_FRAC by gain importance
    print(f"\n=== Phase 2: Feature pruning (keep top {int(KEEP_FRAC*100)}%) ===")
    pruned_features = {}
    for layer in ["rna", "prot", "met"]:
        survivors = prune_features(blocks[layer]["X"], blocks[layer]["y"], layer)
        pruned_features[layer] = survivors

    # Phase 3: rebuild blocks on pruned features, CV again
    print(f"\n=== Phase 3: CV on pruned panel ===")
    pruned_blocks = {}
    oof_dict, ids_dict, y_dict, layer_aucs = {}, {}, {}, {}
    for layer in ["rna", "prot", "met"]:
        feats = pruned_features[layer]
        X = blocks[layer]["X"][feats]
        y = blocks[layer]["y"]
        ids = blocks[layer]["ids"]
        pruned_blocks[layer] = {"X": X, "y": y, "ids": ids}
        oof, auc = cv_layer(X, y, layer)
        oof_dict[layer], ids_dict[layer], y_dict[layer], layer_aucs[layer] = oof, ids, y, auc

    # Fusion on pruned
    fusion = fuse(oof_dict, ids_dict, y_dict)

    # Train final sub-models on full discovery (pruned features)
    sub_models = {}
    for layer in ["rna", "prot", "met"]:
        X, y = pruned_blocks[layer]["X"], pruned_blocks[layer]["y"]
        spw = (y == 0).sum() / max((y == 1).sum(), 1) if BALANCE_METHOD == "scale_pos_weight" else 1.0
        if BALANCE_METHOD == "synthetic":
            X, y = synthetic_balance(X, y)
        m = XGBClassifier(**make_sub_params(spw), random_state=SEED_BASE)
        m.fit(X, y)
        sub_models[layer] = m

    #External validation
    print(f"\n External validation")
    externals = {}
    externals["CGGA"] = {"label": 1, "matrices": {
        "rna":  _load_by_symbol(EXTERNAL_DIR / "CGGA" / "CGGA_IDH_A_RNAseq_RSEM_20250915.txt", panel["rna"], feat_col="Gene"),
        "prot": _load_cgga_prot(panel["prot"]),
        "met":  None}}

    for cohort, prefix, has_normal in [("BRCA", "BRCA", False),
                                       ("CCRCC", "CCRCC", True),
                                       ("LUAD", "LUAD", True)]:
        for kind in (["Tumor", "Normal"] if has_normal else ["Tumor"]):
            externals[f"{cohort}_{kind.lower()}"] = {"label": 0, "matrices": {
                "rna":  _load_by_ensg(EXTERNAL_DIR / cohort / f"{prefix}_RNAseq_gene_RSEM_coding_UQ_1500_log2_{kind}.txt", panel["rna"], sym2ensg),
                "prot": _load_by_ensg(EXTERNAL_DIR / cohort / f"{prefix}_proteomics_gene_abundance_log2_reference_intensity_normalized_{kind}.txt", panel["prot"], sym2ensg),
                "met":  None}}

    for kind, fkind in [("Tumor", "tumor"), ("Normal", "normal")]:
        externals[f"PDAC_{fkind}"] = {"label": 0, "matrices": {
            "rna":  _load_by_symbol(DISCOVERY_DIR / f"mRNA_RSEM_UQ_log2_{kind}.cct.csv", panel["rna"], feat_col="Unnamed: 0", sep=","),
            "prot": _load_by_symbol(DISCOVERY_DIR / f"proteomics_gene_level_MD_abundance_{fkind}.cct.csv", panel["prot"], feat_col="Unnamed: 0", sep=","),
            "met":  None}}

    # Z-score parameter dispatch by layer
    z_params = {"rna": (rna_mu, rna_sd), "prot": (prot_mu, prot_sd), "met": (met_mu, met_sd)}

    ext_results = {}
    for name, info in externals.items():
        # Apply log1p where needed, then z-score, then subset to pruned features
        z_mats = {}
        for layer, raw in info["matrices"].items():
            if raw is None:
                z_mats[layer] = None
                continue
            transformed, did_log = maybe_log1p(raw) if layer == "rna" else (raw, False)
            mu, sd = z_params[layer]
            z = apply_zscore(transformed, mu, sd)
            # Keep ONLY the pruned features that the sub-model was trained on
            feats = pruned_features[layer]
            z = z.loc[[f for f in feats if f in z.index]]
            # Reindex to ensure column order matches sub_model input
            z = z.reindex(feats)
            z_mats[layer] = z
        scored = score_external(z_mats, sub_models, fusion["model"], fusion["youden"])
        if scored is None or scored.empty:
            print(f"  {name:20s}  (no usable samples)"); continue
        scored.to_csv(OUT_DIR / f"external_{name}.csv", index=False)
        n = len(scored)
        mean_p, std_p = scored["P_fused"].mean(), scored["P_fused"].std()
        if info["label"] == 1:
            correct = (scored["call_GBM"] == 1).mean() * 100
            verdict = f"sensitivity={correct:.1f}%"
        else:
            correct = (scored["call_GBM"] == 0).mean() * 100
            verdict = f"specificity={correct:.1f}%"
        # panel coverage for the pruned set
        n_rna  = z_mats["rna"].notna().any(axis=1).sum()  if z_mats["rna"]  is not None else 0
        n_prot = z_mats["prot"].notna().any(axis=1).sum() if z_mats["prot"] is not None else 0
        print(f"  {name:20s}  n={n:3d}  pruned: RNA={n_rna}/{len(pruned_features['rna'])} Prot={n_prot}/{len(pruned_features['prot'])}  "
              f"P(GBM)={mean_p:.3f}±{std_p:.3f}  {verdict}")
        ext_results[name] = {"label": info["label"], "n": n,
                             "mean_p": float(mean_p), "std_p": float(std_p),
                             "correct_pct": float(correct),
                             "panel_rna_found": int(n_rna), "panel_prot_found": int(n_prot)}

    # Lock pipeline
    pipeline = {
        "version": "v11",
        "balance_method": BALANCE_METHOD,
        "diablo_panel_full": panel,
        "pruned_features": pruned_features,
        "sub_models": sub_models,
        "fusion_model": fusion["model"],
        "youden_threshold": fusion["youden"],
        "zscore_params": {
            "rna":  {"mean": rna_mu.to_dict(),  "std": rna_sd.to_dict()},
            "prot": {"mean": prot_mu.to_dict(), "std": prot_sd.to_dict()},
            "met":  {"mean": met_mu.to_dict(),  "std": met_sd.to_dict()},
        },
        "rna_log1p_required": True,  # raw counts → log1p before z-score
        "discovery_metrics": {
            "rna_oof_auc":  layer_aucs["rna"], "prot_oof_auc": layer_aucs["prot"],
            "met_oof_auc":  layer_aucs["met"], "fusion_auc":   fusion["auc"],
            "fusion_pr":    fusion["pr"],      "fusion_sens":  fusion["sens"],
            "fusion_spec":  fusion["spec"]},
        "symbol_to_ensg": sym2ensg,
    }
    pkl = OUT_DIR / "MOmics_v11_locked_pipeline.pkl"
    joblib.dump(pipeline, pkl)
    print(f"\n=== Locked pipeline → {pkl} ===")

    summary = {"version": "v11", "balance_method": BALANCE_METHOD,
               "diablo_panel": panel, "pruned_features": pruned_features,
               "discovery": {"n_tumor": int(sum(manifest.values())),
                             "n_normal": int(len(manifest) - sum(manifest.values())),
                             **pipeline["discovery_metrics"]},
               "external": ext_results}
    with open(OUT_DIR / "v11_summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=float)

    # Figure
    if ext_results:
        fig, ax = plt.subplots(figsize=(11, 5))
        names, means, stds, labels = [], [], [], []
        for n, r in ext_results.items():
            names.append(f"{n}\n(n={r['n']})"); means.append(r["mean_p"])
            stds.append(r["std_p"]); labels.append(r["label"])
        colors = ["#2b8a3e" if lab == 1 else "#c92a2a" for lab in labels]
        ax.bar(names, means, yerr=stds, color=colors, alpha=0.85, capsize=4)
        ax.axhline(fusion["youden"], ls=":", color="black", lw=1.2,
                   label=f"Youden thr = {fusion['youden']:.2f}")
        ax.axhline(0.5, ls="--", color="gray", lw=0.8, alpha=0.6)
        ax.set_ylabel("Mean P(GBM)")
        ax.set_ylim(0, 1.05)
        ax.set_title(f"MOmics v11 ({BALANCE_METHOD})  —  External validation\n"
                     "green = expected GBM, red = expected non-GBM")
        ax.legend(loc="upper right")
        plt.xticks(rotation=30, ha="right")
        plt.tight_layout()
        plt.savefig(OUT_DIR / f"v11_{BALANCE_METHOD}_external.png", dpi=150)
        plt.close()

    return summary


if __name__ == "__main__":
    main()

#disregard all BRCA and LUAD scores.

# MOmics-ML v11 - comprehensive paper figures

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
from sklearn.metrics import confusion_matrix, brier_score_loss
from sklearn.calibration import calibration_curve

# robust pd.read_csv
_pd_read_csv_truly_original = getattr(pd.read_csv, "__momics_wrapped__", pd.read_csv)
def _safe_read_csv(*args, **kwargs):
    if "encoding" in kwargs:
        return _pd_read_csv_truly_original(*args, **kwargs)
    for extra in [dict(encoding="utf-8"), dict(encoding="latin-1"),
                  dict(encoding="utf-8", on_bad_lines="skip"),
                  dict(encoding="latin-1", on_bad_lines="skip"),
                  dict(encoding="latin-1", on_bad_lines="skip", engine="python")]:
        try:
            return _pd_read_csv_truly_original(*args, **{**extra, **kwargs})
        except (UnicodeDecodeError, UnicodeError, pd.errors.ParserError):
            continue
    return _pd_read_csv_truly_original(*args, **kwargs)
_safe_read_csv.__momics_wrapped__ = _pd_read_csv_truly_original
pd.read_csv = _safe_read_csv

RUN_DIR  = OUT_DIR
PKL_PATH = RUN_DIR / "MOmics_v11_locked_pipeline.pkl"
FIG_DIR  = PROJECT_ROOT / "results" / "v11_paper_figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 110, "savefig.dpi": 200,
    "axes.spines.top": False, "axes.spines.right": False, "font.size": 11,
})
COLORS = {"rna": "#2271B1", "prot": "#A03070", "met": "#358B5A"}
LAYER_LABEL = {"rna": "RNA", "prot": "Proteomics", "met": "Metabolomics"}

# Load pipeline + external scores
print("Loading locked pipeline...")
pipe = joblib.load(PKL_PATH)
panel_full   = pipe["diablo_panel_full"]
pruned       = pipe["pruned_features"]
sub_models   = pipe["sub_models"]
fusion_model = pipe["fusion_model"]
threshold    = pipe["youden_threshold"]
z_params     = pipe["zscore_params"]
sym2ensg     = pipe["symbol_to_ensg"]

external = {}
for f in sorted(RUN_DIR.glob("external_*.csv")):
    name = f.stem.replace("external_", "")
    external[name] = pd.read_csv(f)
print(f"Loaded {len(external)} external cohorts")


# FIGURE 1: Top active biomarkers (combined)
print("\nFigure 1: top active biomarkers")
records = []
for layer in ["rna", "prot", "met"]:
    for f, v in zip(pruned[layer], sub_models[layer].feature_importances_):
        records.append({"feature": f, "layer": layer, "importance": float(v),
                         "label": f"{f} ({LAYER_LABEL[layer]})"})
df_imp = pd.DataFrame(records).sort_values("importance", ascending=False).reset_index(drop=True)
df_active = df_imp[df_imp["importance"] > 0].reset_index(drop=True)
top_n = df_active.head(10)

fig, ax = plt.subplots(figsize=(8.5, 5.5))
plot = top_n.iloc[::-1]
bars = ax.barh(plot["label"], plot["importance"],
               color=[COLORS[l] for l in plot["layer"]],
               edgecolor="black", linewidth=0.4, alpha=0.9)
for bar, val in zip(bars, plot["importance"]):
    ax.text(val + 0.008, bar.get_y() + bar.get_height()/2,
            f"{val:.3f}", va="center", fontsize=9.5)
ax.set_xlabel("Gain importance (within-layer normalized)", fontsize=11)
ax.set_title(f"Active multi-omic biomarkers ({len(df_active)} features) — MOmics-ML v11",
              fontsize=12, pad=10)
ax.legend(handles=[mpatches.Patch(facecolor=COLORS[l], edgecolor="black", linewidth=0.4,
                                   label=LAYER_LABEL[l]) for l in ["rna","prot","met"]],
          loc="lower right", frameon=False, fontsize=10)
ax.set_xlim(0, max(plot["importance"]) * 1.18)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_top10_biomarkers.png", bbox_inches="tight")
plt.show()


# FIGURE 2: Specificity bar chart (CGGA / PDAC / ccRCC)
print("\nFigure 2: specificity bar chart")
target_cohorts = [
    ("CGGA",        "CGGA (Target)",   "#2563A8"),
    ("PDAC_tumor",  "PDAC (Control)",  "#B83A3A"),
    ("CCRCC_tumor", "ccRCC (Control)", "#B83A3A"),
]

fig, ax = plt.subplots(figsize=(8, 5))
names, means_pct, colors_, ns = [], [], [], []
for key, lbl, col in target_cohorts:
    if key not in external: continue
    s = external[key]["P_fused"]
    names.append(f"{lbl}\n(n={len(s)})")
    means_pct.append(s.mean()*100); colors_.append(col); ns.append(len(s))

bars = ax.bar(names, means_pct, color=colors_, edgecolor="black", linewidth=0.6, width=0.55)
for bar, v in zip(bars, means_pct):
    ax.text(bar.get_x() + bar.get_width()/2, v + 1.5, f"{v:.2f}%",
            ha="center", fontsize=11, fontweight="bold")
ax.axhline(50, ls="--", color="black", lw=1.0, label="Decision Threshold (50%)")
ax.set_ylim(0, 100); ax.set_ylabel("Model Confidence (%)", fontsize=11)
ax.set_title("Specificity Test: GBM Detection vs. Other Cancers", fontsize=12, pad=10)
ax.legend(loc="upper right", frameon=False, fontsize=10)
ax.grid(axis="y", linestyle=":", alpha=0.4); ax.set_axisbelow(True)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_specificity_test.png", bbox_inches="tight")
plt.show()


# FIGURE 3: Violin plots
print("\nFigure 3: violin plots")
violin_order = [
    ("CGGA",          "CGGA",           "#2563A8"),
    ("BRCA_tumor",    "BRCA tumor",     "#B83A3A"),
    ("CCRCC_tumor",   "ccRCC tumor",    "#B83A3A"),
    ("CCRCC_normal",  "ccRCC normal",   "#888888"),
    ("LUAD_tumor",    "LUAD tumor",     "#B83A3A"),
    ("LUAD_normal",   "LUAD normal",    "#888888"),
    ("PDAC_tumor",    "PDAC tumor",     "#B83A3A"),
    ("PDAC_normal",   "PDAC normal",    "#888888"),
]

fig, ax = plt.subplots(figsize=(12, 5.5))
data, labels, fcs, positions = [], [], [], []
for i, (key, lbl, col) in enumerate(violin_order):
    if key not in external: continue
    s = external[key]["P_fused"].dropna().values
    if len(s) == 0: continue
    data.append(s); labels.append(f"{lbl}\nn={len(s)}")
    fcs.append(col); positions.append(i)

parts = ax.violinplot(data, positions=positions, widths=0.85,
                       showmeans=False, showmedians=True, showextrema=False)
for pc, fc in zip(parts["bodies"], fcs):
    pc.set_facecolor(fc); pc.set_alpha(0.6); pc.set_edgecolor("black"); pc.set_linewidth(0.6)

np.random.seed(0)
for i, vals in enumerate(data):
    jitter = (np.random.rand(len(vals)) - 0.5) * 0.18
    ax.scatter(np.full(len(vals), positions[i]) + jitter, vals,
               s=8, color="black", alpha=0.4, zorder=3)

ax.set_xticks(positions); ax.set_xticklabels(labels, rotation=20, ha="right")
ax.axhline(threshold, ls=":", color="red", lw=1.3)
ax.axhline(0.5, ls="--", color="gray", lw=0.8, alpha=0.6)
ax.set_ylabel("P(GBM)", fontsize=11); ax.set_ylim(-0.02, 1.05)
ax.set_title("Per-cohort distribution of model predictions", fontsize=12, pad=10)
ax.legend(handles=[
    mpatches.Patch(facecolor="#2563A8", edgecolor="black", label="GBM (target)"),
    mpatches.Patch(facecolor="#B83A3A", edgecolor="black", label="Other cancer (control)"),
    mpatches.Patch(facecolor="#888888", edgecolor="black", label="Normal tissue (control)"),
    plt.Line2D([0],[0], ls=":", color="red", label=f"Youden threshold = {threshold:.2f}"),
], loc="center right", frameon=False, fontsize=9)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_violin_performance.png", bbox_inches="tight")
plt.show()


# FIGURE 4: Score histograms
print("\nFigure 4: score histograms")
fig, axes = plt.subplots(2, 4, figsize=(15, 7), sharex=True)
axes = axes.flatten()
for i, (key, lbl, col) in enumerate(violin_order):
    if key not in external:
        axes[i].set_visible(False); continue
    s = external[key]["P_fused"].dropna().values
    ax = axes[i]
    ax.hist(s, bins=20, range=(0,1), color=col, alpha=0.75,
            edgecolor="black", linewidth=0.4)
    ax.axvline(threshold, ls=":", color="red", lw=1.2)
    ax.set_title(f"{lbl} (n={len(s)})", fontsize=10)
    ax.set_xlim(0, 1); ax.set_xlabel("P(GBM)", fontsize=9)
    ax.set_ylabel("Frequency", fontsize=9); ax.tick_params(axis="both", labelsize=8)

fig.suptitle("Frequency of prediction scores per cohort", fontsize=13, y=1.00)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_histogram_scores.png", bbox_inches="tight")
plt.show()


# FIGURE 5: Specificity heatmap
print("\nFigure 5: specificity heatmap")
META = {"gene","gene_id","gene_name","gene_type","gene_status","havana_gene",
        "full_length","exon_length","refseq_id","Metabolite","idx",
        "Unnamed: 0","Gene","Protein.Group","Genes","_mean","_ensg","_sym","_g"}

def detect(df, exclude=None):
    return [c for c in df.columns if c not in (exclude or set()) | META]

def filter_to(df, fc, target, sc):
    sub = df[df[fc].isin(target)].copy()
    if sub.empty: return pd.DataFrame(index=target, columns=sc, dtype=float)
    sub["_mean"] = sub[sc].astype(float).mean(axis=1, skipna=True)
    sub = sub.sort_values("_mean", ascending=False).drop_duplicates(fc)
    M = pd.DataFrame(index=target, columns=sc, dtype=float)
    for f in target:
        h = sub[sub[fc] == f]
        if not h.empty: M.loc[f] = h.iloc[0][sc].astype(float).values
    return M

def load_by_ensg(fp, target):
    if not Path(fp).exists(): return None
    df = pd.read_csv(fp, sep="\t", low_memory=False)
    fc = df.columns[0]; sc = detect(df, exclude={fc})
    df["_ensg"] = df[fc].astype(str).str.split(".").str[0]
    target_ensgs = {sym2ensg[s]: s for s in target if s in sym2ensg}
    sub = df[df["_ensg"].isin(target_ensgs)].copy()
    if sub.empty: return pd.DataFrame(index=target, columns=sc, dtype=float)
    sub["_sym"] = sub["_ensg"].map(target_ensgs)
    sub["_mean"] = sub[sc].astype(float).mean(axis=1, skipna=True)
    sub = sub.sort_values("_mean", ascending=False).drop_duplicates("_sym")
    M = pd.DataFrame(index=target, columns=sc, dtype=float)
    for _, r in sub.iterrows(): M.loc[r["_sym"]] = r[sc].astype(float).values
    return M

manifest = {}
for _, r in pd.read_csv(DISCOVERY_DIR / "all_subtypes.v5.1.tsv", sep="\t").iterrows():
    if r["sample_type"] == "tumor":         manifest[r["case"]] = "GBM"
    elif r["sample_type"] == "GTEx normal": manifest[r["case"]] = "Normal"

rna_disc_df = pd.read_csv(DISCOVERY_DIR / "rnaseq_washu_readcount.v4.0.tsv", sep="\t", low_memory=False)
sc_disc = [c for c in rna_disc_df.columns if c in manifest]
rna_disc = np.log1p(filter_to(rna_disc_df, "gene_name", pruned["rna"], sc_disc))

mu = pd.Series(z_params["rna"]["mean"]); sd = pd.Series(z_params["rna"]["std"]).replace(0, 1.0)
def zscore(M):
    out = M.copy()
    for f in out.index:
        if f in mu.index and not pd.isna(mu[f]):
            out.loc[f] = (out.loc[f] - mu[f]) / sd[f]
        else:
            out.loc[f] = np.nan
    return out

rna_disc_z = zscore(rna_disc)
mean_gbm   = rna_disc_z.loc[:, [s for s in sc_disc if manifest[s]=="GBM"]].mean(axis=1)
mean_norm  = rna_disc_z.loc[:, [s for s in sc_disc if manifest[s]=="Normal"]].mean(axis=1)

pdac_rna = pd.read_csv(DISCOVERY_DIR / "mRNA_RSEM_UQ_log2_Tumor.cct.csv", low_memory=False)
fc_p = pdac_rna.columns[0]; sc_p = detect(pdac_rna, exclude={fc_p})
pdac_M = filter_to(pdac_rna, fc_p, pruned["rna"], sc_p)
mean_pdac = zscore(pdac_M).mean(axis=1)

ccrcc_M = load_by_ensg(EXTERNAL_DIR / "CCRCC" / "CCRCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt", pruned["rna"])
mean_ccrcc = zscore(ccrcc_M).mean(axis=1)

heat = pd.DataFrame({
    "GBM tumor\n(discovery)":  mean_gbm,
    "Brain normal\n(GTEx)":    mean_norm,
    "PDAC tumor":              mean_pdac,
    "ccRCC tumor":             mean_ccrcc,
}).loc[pruned["rna"]]

fig, ax = plt.subplots(figsize=(7.5, 4.5))
finite = heat.values[np.isfinite(heat.values)]
vmax = max(abs(finite.min()), abs(finite.max()))
im = ax.imshow(heat.values, cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="auto")
ax.set_xticks(range(heat.shape[1])); ax.set_xticklabels(heat.columns, rotation=20, ha="right")
ax.set_yticks(range(heat.shape[0])); ax.set_yticklabels(heat.index)
for i in range(heat.shape[0]):
    for j in range(heat.shape[1]):
        v = heat.values[i, j]
        if np.isfinite(v):
            ax.text(j, i, f"{v:+.2f}", ha="center", va="center",
                    color="white" if abs(v) > vmax*0.55 else "black", fontsize=9)
ax.set_title("Z-scored RNA biomarker abundance across cohorts\n"
              "(reference = discovery cohort means)", fontsize=11, pad=10)
fig.colorbar(im, ax=ax, fraction=0.04, label="z-score")
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_specificity_heatmap.png", bbox_inches="tight")
plt.show()


# FIGURE 6: Benchmarking RNA-only vs multi-omic (per-cohort)
print("\nFigure 6: benchmarking — per-cohort breakdown")
label_map = {"CGGA": 1, "BRCA_tumor": 0, "CCRCC_tumor": 0, "CCRCC_normal": 0,
              "LUAD_tumor": 0, "LUAD_normal": 0, "PDAC_tumor": 0, "PDAC_normal": 0}
display_names = {"CGGA":"CGGA", "BRCA_tumor":"BRCA tumor", "CCRCC_tumor":"ccRCC tumor",
                  "CCRCC_normal":"ccRCC normal", "LUAD_tumor":"LUAD tumor",
                  "LUAD_normal":"LUAD normal", "PDAC_tumor":"PDAC tumor",
                  "PDAC_normal":"PDAC normal"}

# Compute per-cohort accuracy for both models
def per_cohort_acc(score_col, threshold_use):
    out = {}
    for k, lab in label_map.items():
        if k not in external or score_col not in external[k].columns: continue
        s = external[k][score_col].dropna().values
        if len(s) == 0: continue
        out[k] = ((s >= threshold_use) == lab).mean() * 100
    return out

rna_acc    = per_cohort_acc("P_rna",   0.5)        # default threshold for RNA sub-model
fusion_acc = per_cohort_acc("P_fused", threshold)  # Youden threshold for fusion

# Group bar chart
cohorts_in = [k for k in label_map if k in rna_acc and k in fusion_acc]
x = np.arange(len(cohorts_in))
w = 0.38

fig, ax = plt.subplots(figsize=(12, 5.5))
b1 = ax.bar(x - w/2, [rna_acc[k]    for k in cohorts_in], w,
             color="#2271B1", edgecolor="black", linewidth=0.5,
             label="RNA-only baseline (XGBoost)")
b2 = ax.bar(x + w/2, [fusion_acc[k] for k in cohorts_in], w,
             color="#358B5A", edgecolor="black", linewidth=0.5,
             label="Multi-omic (RNA + Prot + Met)")

for bar, k in zip(b1, cohorts_in):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.0,
            f"{rna_acc[k]:.0f}%", ha="center", fontsize=8.5)
for bar, k in zip(b2, cohorts_in):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.0,
            f"{fusion_acc[k]:.0f}%", ha="center", fontsize=8.5, fontweight="bold")

ax.set_xticks(x)
xtl = []
for k in cohorts_in:
    n = (external[k]["P_fused"].notna()).sum()
    metric = "sens" if label_map[k] == 1 else "spec"
    xtl.append(f"{display_names[k]}\nn={n}, {metric}")
ax.set_xticklabels(xtl, fontsize=9)
ax.set_ylabel("Per-cohort accuracy (%)", fontsize=11)
ax.set_ylim(0, 115)
# Weighted means in title
def weighted_mean(acc_dict):
    total_n = sum((external[k]["P_fused"].notna()).sum() for k in acc_dict)
    return sum(acc_dict[k] * (external[k]["P_fused"].notna()).sum() for k in acc_dict) / total_n
rm = weighted_mean(rna_acc); fm = weighted_mean(fusion_acc)
ax.set_title(f"Benchmarking: RNA-only vs Multi-omic (per-cohort)\n"
              f"Weighted mean accuracy: RNA-only {rm:.1f}%   Multi-omic {fm:.1f}%   "
              f"(Δ = {'+' if fm-rm>=0 else ''}{fm-rm:.1f}%)",
              fontsize=11, pad=10)
ax.legend(loc="upper right", frameon=False, fontsize=10)
ax.grid(axis="y", linestyle=":", alpha=0.4); ax.set_axisbelow(True)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_benchmarking.png", bbox_inches="tight")
plt.show()
print(f"  RNA-only weighted accuracy:  {rm:.2f}%")
print(f"  Multi-omic weighted accuracy: {fm:.2f}%")
print(f"  Δ = {fm-rm:+.2f}%")


# FIGURE 7: Confusion matrix
print("\nFigure 7: confusion matrix")
y_true_all, y_pred_all, y_score_all = [], [], []
for k, lab in label_map.items():
    if k not in external: continue
    s = external[k]["P_fused"].dropna().values
    y_true_all.extend([lab] * len(s))
    y_pred_all.extend((s >= threshold).astype(int).tolist())
    y_score_all.extend(s.tolist())

y_true_arr = np.array(y_true_all)
y_score_arr = np.array(y_score_all)
tn, fp, fn, tp = confusion_matrix(y_true_arr, y_pred_all, labels=[0,1]).ravel()
sens = tp / (tp + fn) if (tp + fn) else 0
spec = tn / (tn + fp) if (tn + fp) else 0
ppv  = tp / (tp + fp) if (tp + fp) else 0
npv  = tn / (tn + fn) if (tn + fn) else 0
acc  = (tp + tn) / len(y_true_all)

# Build 2x2 with rows = predicted, cols = true (clinical convention: predicted on y axis)
cm_display = np.array([[tp, fp],   # row: predicted GBM
                        [fn, tn]])  # row: predicted non-GBM
fig, ax = plt.subplots(figsize=(7, 5.5))
im = ax.imshow(cm_display, cmap="Blues")
labels = [["TP", "FP"], ["FN", "TN"]]
total = cm_display.sum()
for i in range(2):
    for j in range(2):
        v = cm_display[i, j]
        ax.text(j, i, f"{labels[i][j]}\n{v}\n({v/total*100:.1f}%)",
                ha="center", va="center",
                color="white" if v > cm_display.max()*0.5 else "black",
                fontsize=12, fontweight="bold")
ax.set_xticks([0, 1]); ax.set_xticklabels(["True GBM\n(CGGA)",
                                             "True non-GBM\n(other cancers + normals)"])
ax.set_yticks([0, 1]); ax.set_yticklabels(["Predicted GBM",
                                             "Predicted non-GBM"])
ax.set_title(f"Clinical confusion matrix (all external cohorts pooled, n={total})\n"
              f"Sens {sens*100:.1f}%   Spec {spec*100:.1f}%   "
              f"PPV {ppv*100:.1f}%   NPV {npv*100:.1f}%   Acc {acc*100:.1f}%",
              fontsize=10.5, pad=10)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_confusion_matrix.png", bbox_inches="tight")
plt.show()
print(f"  TP={tp}  FP={fp}  TN={tn}  FN={fn}")


# FIGURE 8: Calibration plot (raw + isotonically-calibrated)
print("\nFigure 8: calibration plot")
prob_true_raw, prob_pred_raw = calibration_curve(y_true_arr, y_score_arr, n_bins=10, strategy="quantile")
brier_raw = brier_score_loss(y_true_arr, y_score_arr)

# Apply isotonic calibration on a held-out portion via 5-fold CV-style mapping
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import StratifiedKFold

# Out-of-fold isotonic mapping
y_calibrated = np.zeros_like(y_score_arr)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for tr, te in skf.split(y_score_arr, y_true_arr):
    iso = IsotonicRegression(out_of_bounds="clip")
    iso.fit(y_score_arr[tr], y_true_arr[tr])
    y_calibrated[te] = iso.predict(y_score_arr[te])

prob_true_cal, prob_pred_cal = calibration_curve(y_true_arr, y_calibrated, n_bins=10, strategy="quantile")
brier_cal = brier_score_loss(y_true_arr, y_calibrated)

fig, (axc, axh) = plt.subplots(2, 1, figsize=(7, 7),
                                gridspec_kw={"height_ratios": [3, 1]}, sharex=True)
axc.plot([0, 1], [0, 1], "--", color="gray", lw=1, label="Perfect calibration")
axc.plot(prob_pred_raw, prob_true_raw, "o-", color="#A03070", lw=2, markersize=7,
          label=f"Raw XGBoost  (Brier = {brier_raw:.3f})")
axc.plot(prob_pred_cal, prob_true_cal, "o-", color="#1A6FB5", lw=2, markersize=8,
          label=f"Isotonic calibrated  (Brier = {brier_cal:.3f})")
axc.set_ylabel("Observed fraction GBM", fontsize=11)
axc.set_xlim(0, 1); axc.set_ylim(0, 1)
axc.set_title("Clinical calibration — raw vs isotonic-calibrated probabilities",
               fontsize=11, pad=10)
axc.legend(loc="upper left", frameon=False, fontsize=10)
axc.grid(linestyle=":", alpha=0.4)

axh.hist(y_calibrated[y_true_arr==1], bins=20, range=(0,1), color="#2563A8",
         alpha=0.65, edgecolor="black", linewidth=0.4, label="GBM (target)")
axh.hist(y_calibrated[y_true_arr==0], bins=20, range=(0,1), color="#B83A3A",
         alpha=0.65, edgecolor="black", linewidth=0.4, label="non-GBM (control)")
axh.set_xlabel("Predicted P(GBM) — isotonically calibrated", fontsize=11)
axh.set_ylabel("Sample count", fontsize=10)
axh.legend(loc="upper center", frameon=False, fontsize=9, ncol=2)
axh.set_xlim(0, 1)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig_calibration.png", bbox_inches="tight")
plt.show()
print(f"  Brier score: raw={brier_raw:.3f}  isotonic-calibrated={brier_cal:.3f}  "
       f"(lower = better; 0 = perfect, 0.25 = random)")

print(f"\n=== All 8 figures saved to: {FIG_DIR} ===")